;   Copyright (c) Shantanu Kumar. All rights reserved.
;   The use and distribution terms for this software are covered by the
;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;   which can be found in the file LICENSE at the root of this distribution.
;   By using this software in any fashion, you are agreeing to be bound by
;   the terms of this license.
;   You must not remove this notice, or any other, from this software.


(ns ring-sse-middleware.test-util
  (:require
    [clojure.test :refer :all]
    [cheshire.core :as cheshire]))


(defn handler
  [request]
  (println "Request:" request)
  {:status 200
   :headers {"Content-Type" "application/json"}
   :body (cheshire/generate-string
           (-> request
             (dissoc
               :aleph.http/channel :pool  ; generated by Aleph/Manifold
               :async-channel             ; generated by HTTP-Kit
               :server-exchange           ; generated by Immutant
               :body)
             (assoc :now-millis (System/currentTimeMillis))))})
